export interface ITransactionDetails {
  rrn: string;
  responseCode: string;
  responseMessage: string;
  onlinePin: boolean;
  amount: number;
  currencyCode: string;
  merchantName: string;
  originalMerchantName: string;
  merchantAddress: string;
  merchantId: string | null | undefined;
  terminalId: string;
  transactionTime: Date;
  handlerResponseTime: Date | null;
  stan: string;
  authCode: string;
  merchantCategoryCode: string;
  handlerUsed: string;
  MTI: string;
  maskedPan: string;
  cardExpiry: string;
  cardName: string;
  customerRef: string | null | undefined;
  pnr: string | null | undefined;
  version: string | null | undefined;
  location: string | null | undefined;
  clientReference: string;
  processingCode: string;
  notified: boolean;
  settlementStatus: string | boolean;
  flagged: boolean;
  write2pos: boolean;
  script: string;
  FIIC: string;
  customDataElements: string;
  bankName: string;
  cardScheme: string;
  tranType: string;
  vasData: any;
  isRequestPadded: boolean;
  // Extra fields added during flow
  terminalHost?: string;
  switchTerminalId?: string;
  region?: string;
  state?: string;
  substate?: string;
  terminalOwnerName?: string;
  terminalOwnerCode?: string;
  terminalGroupName?: string;
  merchantType?: string;
  ISOResponse?: any;
  transactingTerminalId?: string;
}